server:
  port: 1020
  servlet:
    context-path: /user

spring:
  application:
    name: User-Profile
  datasource:
    url: jdbc:mysql://localhost:3306/progra?UseSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1010/eureka/

